name: "PR Title Check"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: DylanVann/check-pull-request-title@v1
        with:
          regex: '^(feat|fix|docs|chore): .+'
          errorMessage: |
            ❌ Invalid PR title.

            Your PR title must follow:
            **feat: description**
            or
            **fix: description**

            Examples:
            - feat: support multi-select
            - fix: crash when saving form
